server:
  port: ${FREEROAM_GATEWAY_PORT:8080}

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${FREEROAM_EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: freeroam-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: freeroam-summits-service
          uri: lb://FREEROAM-SUMMITS-SERVICE
          predicates:
            - Path=/api/summits/**
          filters:
            - StripPrefix=2
            - TokenRelay=
        - id: freeroam-trails-service
          uri: lb://FREEROAM-TRAILS-SERVICE
          predicates:
            - Path=/api/trails/**
          filters:
            - StripPrefix=2
            - TokenRelay=

  security:
    oauth2:
      client:
        provider:
          gateway-provider:
            issuer-uri: ${FREEROAM_OAUTH2_KEYCLOAK_ISSUER_URI}
        registration:
          freeroam_gateway:
            provider: gateway-provider
            client-id: ${FREEROAM_OAUTH2_KEYCLOAK_CLIENT_ID}
            client-secret: ${FREEROAM_OAUTH2_KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, freeroam_summits_read, freeroam_summits_write
logging:
  level:
    root: warn