server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: freeroam-gateway-server
    cloud:
        gateway:
        routes:
          - id: auth-service
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/api/v1/auth/**
            filters:
              - StripPrefix=2

          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/user/**
            filters:
              - StripPrefix=2
              - TokenRelay=

          - id: summits-service
            uri: lb://SUMMITS-SERVICE
            predicates:
              - Path=/api/v1/summits/**
            filters:
              - StripPrefix=2
              - TokenRelay=